--DATABASE PHẦN MỀM QUẢN LÝ BÁN VÉ CHUYẾN BAY
--chọn tất cả -> excute, không chạy được thì excute 2 lần

CREATE DATABASE QLBVCB
GO
USE QLBVCB
GO
--BẢNG TÀI KHOẢN
CREATE TABLE TAIKHOAN(
USERNAME CHAR(30) UNIQUE NOT NULL, --TÊN TÀIKHOẢN
PASSWORD CHAR(30) UNIQUE NOT NULL, --MẬT KHẨU
HOVATEN NVARCHAR(50) NOT NULL, --HỌ VÀ TÊN
NGAYSINH DATE NOT NULL, --NGÀY SINH
GIOITINH NVARCHAR(3), --GIƠI TÍNH
DIACHI NVARCHAR(100) NOT NULL, --ĐỊA CHỈ
SODIENTHOAI CHAR(20) NOT NULL, --SỐ ĐIỆN THOẠI
CHUCVU NVARCHAR(20) NOT NULL, --CHỨC VỤ
EMAIL CHAR(50) NOT NULL, --EMAIL 
CONSTRAINT PK_USERNAME PRIMARY KEY(USERNAME)
)
GO
--BẢNG LỊCH CHUYẾN BAY
CREATE TABLE LICHCHUYENBAY(
MACHUYENBAY CHAR(30) NOT NULL, --MÃ CHUYẾN BAY
GIAVE DECIMAL NOT NULL, --GIÁ VÉ
SANBAYDI NVARCHAR(100) NOT NULL, --SÂN BAY ĐI
SANBAYDEN NVARCHAR(100) NOT NULL, --SÂN BAY ĐẾN
SANBAYTRUNGGIAN NVARCHAR(100), --SÂN BAY TRUNG GIAN
THOIGIANDUNG TIME NOT NULL, --THỜI GIAN DỪNG
NGAYGIO DATE NOT NULL, --NGÀY GIỜ
THOIGIANBAY TIME NOT NULL, --THỜI GIAN BAY
SOLUONGGHEHANG1 DECIMAL NOT NULL, --SỐ LƯUỌNG GHẾ HẠNG 1
SOLUONGGHEHANG2 DECIMAL NOT NULL, --SỐ LƯỢNG GHẾ HẠNG 2
GHICHU NVARCHAR(200), --GHI CHÚ
CONSTRAINT PK_MACHUYENBAY PRIMARY KEY(MACHUYENBAY)
)
GO
--BẢNG VÉ CHUYẾN BAY
CREATE TABLE VECHUYENBAY(
MAVE CHAR(30) UNIQUE NOT NULL, --MÃ VÉ
MACHUYENBAY CHAR(30) NOT NULL, --MÃ CHUYẾN BAY
HANHKHACH NVARCHAR(50) NOT NULL, --HÀNH KHÁCH
CMND CHAR(40) UNIQUE NOT NULL, --CHỨNG MINH NHÂN DÂN
DIENTHOAI CHAR(30) NOT NULL, --ĐIỆN THOẠI
HANGVE CHAR(5) NOT NULL, --HẠNG VÉ
GIATIEN DECIMAL NOT NULL, --GIÁ TIỀN
CONSTRAINT PK_MAVE PRIMARY KEY(MAVE),
CONSTRAINT FK_VCB_MACB FOREIGN KEY(MACHUYENBAY) REFERENCES LICHCHUYENBAY(MACHUYENBAY)
)
GO
--BẢNG PHIẾU ĐẶT CHỖ
CREATE TABLE PHIEUDATCHO(
MAPHIEUDAT CHAR(30) UNIQUE NOT NULL, --MÃ PHIẾU ĐẶT
MACHUYENBAY CHAR(30) NOT NULL, --MÃ CHUYẾN BAY
HANHKHACH NVARCHAR(50) NOT NULL, --HÀNH KHÁCH
CMND CHAR(40) UNIQUE NOT NULL, --CHỨNG MINH NHÂN DÂN
DIENTHOAI CHAR(30) NOT NULL, --ĐIỆN THOẠI
HANGVE CHAR(5) NOT NULL, --HẠNG VÉ
GIATIEN DECIMAL NOT NULL, --GIÁ TIỀN
CONSTRAINT PK_MAPHIEUDAT PRIMARY KEY(MAPHIEUDAT),
CONSTRAINT FK_PDC_MACB FOREIGN KEY(MACHUYENBAY) REFERENCES LICHCHUYENBAY(MACHUYENBAY)
)
GO
--BẢNG BÁO CÁO DOANH THU BÁN VÉ CÁC CHUYẾN BAY THEO THÁNG
CREATE TABLE DOANHTHUTHANG(
THANG DATE NOT NULL, --THÁNG
MACHUYENBAY CHAR(30) NOT NULL, --MÃ CHUYẾN BAY
SOVE DECIMAL NOT NULL, --SỐ VÉ
DOANHTHU DECIMAL NOT NULL, --SỐ VÉ
TILE CHAR(30) --TỈ LỆ
)
GO
--BẢNG BÁO CÁO DOANH THU NĂM
CREATE TABLE DOANHTHUNAM(
NAM DATE NOT NULL, --NĂM
THANG DATE NOT NULL, --THÁNG
SOCHUYENBAY DECIMAL NOT NULL, --SỐ CHUYẾN BAY
DOANHTHU DECIMAL NOT NULL, --DOANH THU
TILE CHAR(30) --TỈ LỆ
)
GO
--BẢNG SÂN BAY (DÙNG ĐỂ LƯU SỐ LƯỢNG SÂN BAY)
CREATE TABLE SANBAY(
MASANBAY CHAR(30) NOT NULL,
TENSANBAY NVARCHAR(100) NOT NULL,
CONSTRAINT PK_MASANBAY PRIMARY KEY(MASANBAY)
)
GO
--BẢNG SÂN BAY TRUNG GIAN
CREATE TABLE SANBAYTG(
MASBTG CHAR(30) NOT NULL,
TENSBTG NVARCHAR(100) NOT NULL,
TRANGTHAI NVARCHAR(100),
CONSTRAINT PK_MASANBAY PRIMARY KEY(MASBTG)
)
GO

--PROCEDURE CHO TAI KHOAN
CREATE PROCEDURE sp_login
    @Username NVARCHAR(50),
    @Password NVARCHAR(50)
AS
BEGIN
    SET NOCOUNT ON;
    SELECT COUNT(1) 
    FROM dbo.TAIKHOAN
    WHERE USERNAME = @Username AND PASSWORD = @Password;
END
GO